apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: sidecar
    image: almalinux:8
    # if you don't give this command inside alma container it will exit.now upto 200 sec container will be alive. nginx will be running automatically for infinite time until we stop
    command: ["sleep", "200"] 
    