apiVersion: v1
kind: Secret
metadata: 
 name: secret-basic-auth
data:
  username: ZGV2aQo= #encoded value of UN
  password: c29oaXQxMjMK
---
apiVersion: v1
kind: Pod
metadata: 
 name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    # envFrom:
    # - secretRef:
    #     name: secret-basic-auth # getting all secret values at a time
    # to get individual secret values
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: secret-basic-auth
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-basic-auth
          key: password